######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 18 09:35:23 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += readSBML.cpp
